name: Feature request
description: Suggest an improvement or new feature
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: idea
    attributes:
      label: What would you like to see?
      placeholder: "Example: Add a snooze button for 15 minutes..."
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why is it useful?
      placeholder: "Explain the user benefit."
    validations:
      required: true
